resolver: lts-11.13

packages:
- '.'

- location:
    git: https://github.com/haskell-distributed/distributed-process-systest.git
    commit: b4a6b646adb6c81725ddac4babcfc21b86944d98
  extra-dep: true

extra-deps:
- distributed-process-0.7.3
- distributed-process-async-0.2.6
- distributed-process-extras-0.3.5
- rematch-0.2.0.0
